server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
  profiles: prod
person:
  lastName: zhangsan${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: ${person.hello:hello}-小狗
    age: 2

